repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        require_serial: true
        types: [python]
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        args: [--fix]
        language: python
        require_serial: true
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        require_serial: true
        types: [python]
exclude: '_pb2.py$'